FROM python:3.8

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY . /app

CMD jupyter nbconvert --to python ReCell_SupervisedML.ipynb

CMD python ReCell_SupervisedML.py

CMD flask run --host 0.0.0.0 --port 5000